export default {
  Bodies: {
    questions: ['Skinny', 'Chubby', 'Small breasts', 'Large breasts', 'Small cocks', 'Large cocks'],
  },
  Clothing: {
    subsections: ['Self', 'Partner'],
    questions: {
      Self: [
        'Clothed sex',
        'Lingerie',
        'Stockings',
        'Heels',
        'Leather',
        'Latex',
        'Uniform / costume',
        'Cross-dressing',
      ],
      Partner: [
        'Clothed sex',
        'Lingerie',
        'Stockings',
        'Heels',
        'Leather',
        'Latex',
        'Uniform / costume',
        'Cross-dressing',
      ],
    },
  },
  Groupings: {
    questions: [
      'You and 1 male',
      'You and 1 female',
      'You and MtF trans',
      'You and FtM trans',
      'You and 1 male, 1 female',
      'You and 2 males',
      'You and 2 females',
      'Orgy',
    ],
  },
  General: {
    subsections: ['Giving', 'Receiving'],
    questions: {
      Giving: [
        'Romance / Affection',
        'Handjob / fingering',
        'Blowjob',
        'Deep throat',
        'Swallowing',
        'Facials',
        'Cunnilingus',
        'Face-sitting',
        'Edging',
        'Teasing',
        'JOI, SI',
      ],
      Receiving: [
        'Romance / Affection',
        'Handjob / fingering',
        'Blowjob',
        'Deep throat',
        'Swallowing',
        'Facials',
        'Cunnilingus',
        'Face-sitting',
        'Edging',
        'Teasing',
        'JOI, SI',
      ],
    },
  },
  'Ass play': {
    subsections: ['Giving', 'Receiving'],
    questions: {
      Giving: ['Anal toys', 'Anal sex, pegging', 'Rimming', 'Double penetration', 'Anal fisting'],
      Receiving: [
        'Anal toys',
        'Anal sex, pegging',
        'Rimming',
        'Double penetration',
        'Anal fisting',
      ],
    },
  },
  Restrictive: {
    subsections: ['Self', 'Partner'],
    questions: {
      Self: [
        'Gag',
        'Collar',
        'Leash',
        'Chastity',
        'Bondage (Light)',
        'Bondage (Heavy)',
        'Encasement',
      ],
      Partner: [
        'Gag',
        'Collar',
        'Leash',
        'Chastity',
        'Bondage (Light)',
        'Bondage (Heavy)',
        'Encasement',
      ],
    },
  },
  Toys: {
    subsections: ['Self', 'Partner'],
    questions: {
      Self: ['Dildos', 'Plugs', 'Vibrators', 'Sounding'],
      Partner: ['Dildos', 'Plugs', 'Vibrators', 'Sounding'],
    },
  },
  Domination: {
    subsections: ['Dominant', 'Submissive'],
    questions: {
      Dominant: [
        'Dominant / Submissive',
        'Domestic servitude',
        'Slavery',
        'Pet play',
        'DD/lg, MD/lb',
        'Discipline',
        'Begging',
        'Forced orgasm',
        'Orgasm control',
        'Orgasm denial',
        'Power exchange',
      ],
      Submissive: [
        'Dominant / Submissive',
        'Domestic servitude',
        'Slavery',
        'Pet play',
        'DD/lg, MD/lb',
        'Discipline',
        'Begging',
        'Forced orgasm',
        'Orgasm control',
        'Orgasm denial',
        'Power exchange',
      ],
    },
  },
  'No consent': {
    subsections: ['Aggressor', 'Target'],
    questions: {
      Aggressor: [
        'Non-con / rape',
        'Blackmail / coercion',
        'Kidnapping',
        'Drugs / alcohol',
        'Sleep play',
      ],
      Target: [
        'Non-con / rape',
        'Blackmail / coercion',
        'Kidnapping',
        'Drugs / alcohol',
        'Sleep play',
      ],
    },
  },
  Taboo: {
    questions: [
      'Incest',
      'Ageplay',
      'Interracial / Raceplay',
      'Bestiality',
      'Necrophilia',
      'Cheating',
      'Exhibitionism',
      'Voyeurism',
    ],
  },
  Surrealism: {
    subsections: ['Self', 'Partner'],
    questions: {
      Self: ['Futanari', 'Furry', 'Vore', 'Transformation', 'Tentacles', 'Monster or Alien'],
      Partner: ['Futanari', 'Furry', 'Vore', 'Transformation', 'Tentacles', 'Monster or Alien'],
    },
  },
  Fluids: {
    questions: ['Blood', 'Watersports', 'Scat', 'Lactation', 'Diapers', 'Cum play'],
  },
  Degradation: {
    subsections: ['Giving', 'Receiving'],
    questions: {
      Giving: ['Glory hole', 'Name calling', 'Humiliation'],
      Receiving: ['Glory hole', 'Name calling', 'Humiliation'],
    },
  },
  'Touch & Stimulation': {
    subsections: ['Actor', 'Subject'],
    questions: {
      Actor: [
        'Cock/Pussy worship',
        'Ass worship',
        'Foot play',
        'Tickling',
        'Sensation play',
        'Electro stimulation',
      ],
      Subject: [
        'Cock/Pussy worship',
        'Ass worship',
        'Foot play',
        'Tickling',
        'Sensation play',
        'Electro stimulation',
      ],
    },
  },
  'Misc. Fetish': {
    subsections: ['Giving', 'Receiving'],
    questions: {
      Giving: [
        'Fisting',
        'Gangbang',
        'Breath play',
        'Impregnation',
        'Pregnancy',
        'Feminization',
        'Cuckold / Cuckquean',
      ],
      Receiving: [
        'Fisting',
        'Gangbang',
        'Breath play',
        'Impregnation',
        'Pregnancy',
        'Feminization',
        'Cuckold / Cuckquean',
      ],
    },
  },
  Pain: {
    subsections: ['Giving', 'Receiving'],
    questions: {
      Giving: [
        'Light pain',
        'Heavy pain',
        'Nipple clamps',
        'Clothes pins',
        'Caning',
        'Flogging',
        'Beating',
        'Spanking',
        'Cock/Pussy slapping',
        'Cock/Pussy torture',
        'Hot Wax',
        'Scratching',
        'Biting',
        'Cutting',
      ],
      Receiving: [
        'Light pain',
        'Heavy pain',
        'Nipple clamps',
        'Clothes pins',
        'Caning',
        'Flogging',
        'Beating',
        'Spanking',
        'Cock/Pussy slapping',
        'Cock/Pussy torture',
        'Hot Wax',
        'Scratching',
        'Biting',
        'Cutting',
      ],
    },
  },
};
